name: reforma360
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  go_router: ^13.0.1
  flutter_riverpod: 2.6.1
  http: ^1.3.0
  shared_preferences: ^2.0.17
  image_picker: ^0.8.7+4 
  file_picker: ^5.2.5    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gherkin: ^2.0.0
  test: any
  build_runner: any
  mockito: ^5.0.0 # (opcional para mocks)
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
