// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_9_R3PpkcGcC8gRFq8Z7FDDCD20P7OQw',
    appId: '1:609095987738:web:236182cc213af93dd097a3',
    messagingSenderId: '609095987738',
    projectId: 'myapplication-ecb84844',
    authDomain: 'myapplication-ecb84844.firebaseapp.com',
    storageBucket: 'myapplication-ecb84844.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6TbnnsgvfyCYcsBBG7p5WpO_iixNORE',
    appId: '1:609095987738:android:debea2772b015fd0d097a3',
    messagingSenderId: '609095987738',
    projectId: 'myapplication-ecb84844',
    storageBucket: 'myapplication-ecb84844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8wsLnqePy7Ut1NYGEE76_HqE07Mfdh0I',
    appId: '1:609095987738:ios:e24d177f5f98c9a9d097a3',
    messagingSenderId: '609095987738',
    projectId: 'myapplication-ecb84844',
    storageBucket: 'myapplication-ecb84844.firebasestorage.app',
    iosBundleId: 'com.example.reforma360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8wsLnqePy7Ut1NYGEE76_HqE07Mfdh0I',
    appId: '1:609095987738:ios:e24d177f5f98c9a9d097a3',
    messagingSenderId: '609095987738',
    projectId: 'myapplication-ecb84844',
    storageBucket: 'myapplication-ecb84844.firebasestorage.app',
    iosBundleId: 'com.example.reforma360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_9_R3PpkcGcC8gRFq8Z7FDDCD20P7OQw',
    appId: '1:609095987738:web:2e3ef42ac5f530bfd097a3',
    messagingSenderId: '609095987738',
    projectId: 'myapplication-ecb84844',
    authDomain: 'myapplication-ecb84844.firebaseapp.com',
    storageBucket: 'myapplication-ecb84844.firebasestorage.app',
  );
}
